# Generated by Django 5.1.2 on 2024-10-21 06:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financegoals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financegoal',
            name='id',
            field=models.AutoField(default=uuid.UUID('99e943da-424d-4cca-b2c0-237f1d8dd7ea'), primary_key=True, serialize=False),
        ),
    ]
