# Generated by Django 5.1.2 on 2024-10-21 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financegoals', '0002_alter_financegoal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financegoal',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
